## SwiftUI backend availability and typed-coverage catalog.

import std/[strutils, tables]
import ../types

type
  GuiApiSymbol* = GuiCoverageSymbol

proc toKey(kind: string, name: string): string {.inline.} =
  kind.toLowerAscii() & ":" & name

proc typedSwiftUiSymbols*(): seq[GuiApiSymbol] =
  result = @[
    GuiApiSymbol(name: "Text", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Button", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "VStack", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "HStack", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ZStack", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Group", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Spacer", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Image", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "List", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ForEach", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Form", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Section", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Toggle", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "TextField", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "SecureField", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Picker", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ScrollView", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "NavigationStack", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "NavigationSplitView", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "NavigationLink", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "TabView", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Divider", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "LazyVStack", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "LazyHStack", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "RoundedRectangle", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Capsule", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Rectangle", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ProgressView", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "LinearGradient", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "RadialGradient", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "AngularGradient", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ToolbarItem", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ToolbarItemGroup", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Label", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Menu", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ContentUnavailableView", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Slider", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Stepper", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "DatePicker", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ColorPicker", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "TextEditor", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Link", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ShareLink", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "EmptyView", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "AnyView", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Color", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "GeometryReader", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "LazyVGrid", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "LazyHGrid", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Grid", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "GridRow", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Table", kind: "view", supportsMacOS: true, supportsIOS: false, minMacOS: "13.0", minIOS: "n/a", typed: true),
    GuiApiSymbol(name: "TableColumn", kind: "view", supportsMacOS: true, supportsIOS: false, minMacOS: "13.0", minIOS: "n/a", typed: true),
    GuiApiSymbol(name: "DisclosureGroup", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "OutlineGroup", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "TimelineView", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Canvas", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ViewThatFits", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Gauge", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "MultiDatePicker", kind: "view", supportsMacOS: false, supportsIOS: true, minMacOS: "n/a", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "PhotosPicker", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "LabeledContent", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "GroupBox", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "HSplitView", kind: "view", supportsMacOS: true, supportsIOS: false, minMacOS: "13.0", minIOS: "n/a", typed: true),
    GuiApiSymbol(name: "VSplitView", kind: "view", supportsMacOS: true, supportsIOS: false, minMacOS: "13.0", minIOS: "n/a", typed: true),
    GuiApiSymbol(name: "Circle", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Ellipse", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "Path", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "AsyncImage", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ScrollViewReader", kind: "view", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),

    GuiApiSymbol(name: "padding", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "frame", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "background", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "foregroundColor", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "font", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "fontWeight", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "lineLimit", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "minimumScaleFactor", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "opacity", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "hidden", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "accessibilityLabel", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "accessibilityHint", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "cornerRadius", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "shadow", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "clipShape", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "offset", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "scaleEffect", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "rotationEffect", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "onTapGesture", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "gesture", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "highPriorityGesture", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "simultaneousGesture", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "matchedGeometryEffect", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "onAppear", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "onDisappear", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "disabled", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "layoutPriority", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "zIndex", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "buttonStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "textFieldStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "toggleStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "listStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "scrollContentBackground", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "overlay", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "mask", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "stroke", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "strokeBorder", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "ignoresSafeArea", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "tint", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "searchable", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "toolbar", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "navigationTitle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "navigationSubtitle", kind: "modifier", supportsMacOS: true, supportsIOS: false, minMacOS: "13.0", minIOS: "n/a", typed: true),
    GuiApiSymbol(name: "toolbarBackground", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "toolbarColorScheme", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "toolbarTitleDisplayMode", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "navigationSplitViewStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "preferredColorScheme", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "controlSize", kind: "modifier", supportsMacOS: true, supportsIOS: false, minMacOS: "13.0", minIOS: "n/a", typed: true),
    GuiApiSymbol(name: "labelsHidden", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "listRowSeparator", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "listRowSeparatorTint", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "listRowInsets", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "listRowBackground", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "tag", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "pickerStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "safeAreaInset", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "scrollIndicators", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "scrollDismissesKeyboard", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "textSelection", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "allowsHitTesting", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "onChange", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "onSubmit", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "onLongPressGesture", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "onDrag", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "onDrop", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "sheet", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "fullScreenCover", kind: "modifier", supportsMacOS: false, supportsIOS: true, minMacOS: "n/a", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "alert", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "confirmationDialog", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "popover", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "contextMenu", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "swipeActions", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "animation", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "transition", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "task", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "refreshable", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "fixedSize", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "aspectRatio", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "clipped", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "border", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "blur", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "brightness", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "contrast", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "saturation", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "grayscale", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "hueRotation", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "colorMultiply", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "colorInvert", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "help", kind: "modifier", supportsMacOS: true, supportsIOS: false, minMacOS: "13.0", minIOS: "n/a", typed: true),
    GuiApiSymbol(name: "focusable", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "focused", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "badge", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "redacted", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "unredacted", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "multilineTextAlignment", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "navigationDestination", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "environment", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "interactiveDismissDisabled", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "presentationDetents", kind: "modifier", supportsMacOS: false, supportsIOS: true, minMacOS: "n/a", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "presentationDragIndicator", kind: "modifier", supportsMacOS: false, supportsIOS: true, minMacOS: "n/a", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "sensoryFeedback", kind: "modifier", supportsMacOS: false, supportsIOS: true, minMacOS: "n/a", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "contentTransition", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "scrollTargetBehavior", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "scrollPosition", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "foregroundStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "backgroundStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "containerRelativeFrame", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "keyboardShortcut", kind: "modifier", supportsMacOS: true, supportsIOS: false, minMacOS: "13.0", minIOS: "n/a", typed: true),
    GuiApiSymbol(name: "onKeyPress", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "fileImporter", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "fileExporter", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "onDelete", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "onMove", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "deleteDisabled", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "moveDisabled", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "gridCellColumns", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "gridColumnAlignment", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "gridCellAnchor", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    # Text styling
    GuiApiSymbol(name: "bold", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "italic", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "underline", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "strikethrough", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "fontDesign", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "lineSpacing", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "kerning", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "monospaced", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "monospacedDigit", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    # Interaction
    GuiApiSymbol(name: "contentShape", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "onHover", kind: "modifier", supportsMacOS: true, supportsIOS: false, minMacOS: "13.0", minIOS: "n/a", typed: true),
    GuiApiSymbol(name: "onContinuousHover", kind: "modifier", supportsMacOS: true, supportsIOS: false, minMacOS: "13.0", minIOS: "n/a", typed: true),
    # Accessibility
    GuiApiSymbol(name: "accessibilityElement", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "accessibilityValue", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "accessibilityAddTraits", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "accessibilityRemoveTraits", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "accessibilityIdentifier", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "accessibilityHidden", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "accessibilitySortPriority", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    # Symbol rendering
    GuiApiSymbol(name: "symbolRenderingMode", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "symbolVariant", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "imageScale", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    # Style modifiers
    GuiApiSymbol(name: "datePickerStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "progressViewStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "groupBoxStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "labelStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "formStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "tableStyle", kind: "modifier", supportsMacOS: true, supportsIOS: false, minMacOS: "14.0", minIOS: "n/a", typed: true),
    GuiApiSymbol(name: "gaugeStyle", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    # Other
    GuiApiSymbol(name: "accentColor", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "dynamicTypeSize", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "14.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "id", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "tabItem", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "inspector", kind: "modifier", supportsMacOS: true, supportsIOS: false, minMacOS: "14.0", minIOS: "n/a", typed: true),
    GuiApiSymbol(name: "headerProminence", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true),
    GuiApiSymbol(name: "listSectionSeparator", kind: "modifier", supportsMacOS: true, supportsIOS: true, minMacOS: "13.0", minIOS: "17.0", typed: true)
  ]

proc coverageReportForSwiftUi*(opts: GuiCoverageOptions): GuiCoverageReport =
  result.backend = gbkSwiftUI
  result.dialect = opts.dialect
  result.passthroughEnabled = opts.includePassthrough
  result.symbols = typedSwiftUiSymbols()
  for symbol in result.symbols:
    if symbol.kind == "view":
      inc result.typedViewCount
    elif symbol.kind == "modifier":
      inc result.typedModifierCount

proc symbolLookup*(kind: string, name: string): tuple[known: bool, symbol: GuiApiSymbol] =
  var map: Table[string, GuiApiSymbol]
  for symbol in typedSwiftUiSymbols():
    map[toKey(symbol.kind, symbol.name)] = symbol
  let key = toKey(kind, name)
  if key in map:
    return (true, map[key])
  (false, GuiApiSymbol())

proc supportsTarget*(symbol: GuiApiSymbol, target: GuiTargetPlatform): bool =
  case target
  of gtpMacOS:
    symbol.supportsMacOS
  of gtpIOS:
    symbol.supportsIOS
